# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlossingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('examples', models.TextField(blank=True)),
                ('abbr_overrides', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
