# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0004_auto_20160616_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialect',
            name='to_language',
        ),
        migrations.RemoveField(
            model_name='form',
            name='to_lemma',
        ),
        migrations.RemoveField(
            model_name='lemma',
            name='to_language',
        ),
        migrations.RemoveField(
            model_name='normalizationmodel',
            name='to_additional_language',
        ),
        migrations.RemoveField(
            model_name='normalizationmodel',
            name='to_dialect',
        ),
        migrations.RemoveField(
            model_name='token',
            name='to_forms',
        ),
        migrations.RemoveField(
            model_name='tokentoform',
            name='to_form',
        ),
        migrations.RemoveField(
            model_name='tokentoform',
            name='to_token',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='to_dialect',
        ),
        migrations.DeleteModel(
            name='Dialect',
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Lemma',
        ),
        migrations.DeleteModel(
            name='NormalizationModel',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='TokenToForm',
        ),
    ]
