# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:28
from __future__ import unicode_literals

import corpora.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Corpora',
            },
        ),
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('annotation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('POS', models.CharField(max_length=10)),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpora.Language')),
            ],
            options={
                'verbose_name_plural': 'Lemmata',
            },
        ),
        migrations.CreateModel(
            name='NormalizationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examples', models.TextField(blank=True)),
                ('exceptions', models.TextField(blank=True)),
                ('to_additional_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpora.Language')),
                ('to_dialect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpora.Dialect')),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.CharField(max_length=30, verbose_name='Unique ID')),
                ('recording_date', models.DateField(default=django.utils.timezone.now)),
                ('recording_time', models.TimeField(blank=True, null=True)),
                ('data', models.FileField(blank=True, null=True, storage=corpora.models.OverwriteStorage(), upload_to='', verbose_name='Transciption')),
                ('audio', models.FileField(blank=True, null=True, storage=corpora.models.OverwriteStorage(), upload_to='')),
                ('metacomment1', models.CharField(blank=True, max_length=100, verbose_name='MetaComment1')),
                ('metacomment2', models.CharField(blank=True, max_length=100, verbose_name='MetaComment2')),
                ('metacomment3', models.CharField(blank=True, max_length=100, verbose_name='MetaComment3')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('topics', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('informant', models.TextField(verbose_name='OF: informant')),
                ('location', models.TextField(verbose_name='Location')),
                ('recording_device', models.CharField(blank=True, max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('recording_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.Location')),
                ('to_dialect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpora.Dialect', verbose_name='Dialect')),
                ('to_interviewers', models.ManyToManyField(blank=True, to='info.Interviewer', verbose_name='Interviewers')),
                ('to_speakers', models.ManyToManyField(blank=True, to='info.Speaker', verbose_name='Speakers')),
            ],
            options={
                'verbose_name': 'Recording',
                'verbose_name_plural': 'Recordings',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TokenToForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('to_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpora.Form')),
                ('to_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpora.Token')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='to_forms',
            field=models.ManyToManyField(through='corpora.TokenToForm', to='corpora.Form'),
        ),
        migrations.AddField(
            model_name='form',
            name='to_lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpora.Lemma', verbose_name='to lemma(ta)'),
        ),
        migrations.AddField(
            model_name='dialect',
            name='to_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpora.Language'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='to_files',
            field=models.ManyToManyField(to='corpora.Recording', verbose_name='Elan data'),
        ),
    ]
