# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0002_remove_recording_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='participants_field',
            field=models.TextField(blank=True, verbose_name='OF: participants'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='string_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='Unique ID'),
        ),
    ]
