# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpora', '0003_auto_20160615_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='informant',
            field=models.TextField(blank=True, verbose_name='OF: informant'),
        ),
    ]
