# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0002_auto_20160617_1150'),
        ('corpora', '0005_auto_20160617_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='to_dialect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='morphology.Dialect', verbose_name='Dialect'),
        ),
    ]
