# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20160616_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='education_text',
            field=models.TextField(blank=True, verbose_name='Education details'),
        ),
    ]
