# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('morphology', '0002_auto_20160617_1150'),
        ('info', '0006_auto_20160617_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_speaker', models.BooleanField()),
                ('literate', models.BooleanField()),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morphology.Language', verbose_name='Language')),
                ('to_speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Speaker')),
            ],
            options={
                'verbose_name_plural': 'Linguistic Biography',
            },
        ),
        migrations.AddField(
            model_name='speaker',
            name='languages',
            field=models.ManyToManyField(through='info.LanguageRelation', to='morphology.Language'),
        ),
    ]
