# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('patronimic_name', models.CharField(blank=True, max_length=20)),
                ('year_of_birth', models.IntegerField(null=True)),
                ('year_of_enrollment', models.IntegerField(null=True)),
                ('affiliation', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_speaker', models.BooleanField()),
                ('literate', models.BooleanField()),
                ('to_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Language', verbose_name='Language')),
            ],
            options={
                'verbose_name_plural': 'VI. Linguistic Biography',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='LocationRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration of stay (years)')),
                ('place_of_birth', models.BooleanField()),
                ('living', models.BooleanField()),
                ('working', models.BooleanField()),
                ('studying', models.BooleanField()),
                ('military_service', models.BooleanField()),
                ('prison', models.BooleanField()),
                ('details', models.TextField(blank=True, null=True)),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Location', verbose_name='Location')),
            ],
            options={
                'verbose_name_plural': 'Va. Geography of Life',
            },
        ),
        migrations.CreateModel(
            name='PersonalRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'VII. Relations with other speakers',
            },
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('abbreviation', models.CharField(max_length=2)),
                ('assymetric_relation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='info.RelationType', verbose_name='Assymetric reversed relation')),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_id', models.CharField(max_length=30, verbose_name='Speaker ID')),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('patronimic_name', models.CharField(blank=True, max_length=20)),
                ('other_names', models.CharField(blank=True, max_length=40)),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('year_of_birth', models.IntegerField(null=True)),
                ('year_of_death', models.IntegerField(blank=True, null=True)),
                ('pob', models.CharField(blank=True, max_length=200, verbose_name='Old Field: Place of Birth')),
                ('por', models.CharField(blank=True, max_length=200, verbose_name='Old Field: Residence')),
                ('pofr', models.CharField(blank=True, max_length=200, verbose_name='Old Field: Former Residence')),
                ('mob', models.CharField(blank=True, max_length=80, verbose_name='Old Field: Mobility')),
                ('mobility', models.IntegerField(blank=True, null=True)),
                ('education_text', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=200)),
                ('relatives', models.CharField(max_length=200, verbose_name='Old Field: Relatives')),
                ('parents', models.CharField(max_length=200, verbose_name='Old Field: Parents')),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('details', models.TextField(blank=True)),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.EducationType')),
                ('languages', models.ManyToManyField(through='info.LanguageRelation', to='info.Language')),
                ('locations', models.ManyToManyField(through='info.LocationRelation', to='info.Location')),
                ('relations', models.ManyToManyField(through='info.PersonalRelation', to='info.Speaker')),
            ],
        ),
        migrations.AddField(
            model_name='personalrelation',
            name='from_speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Speaker'),
        ),
        migrations.AddField(
            model_name='personalrelation',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.RelationType'),
        ),
        migrations.AddField(
            model_name='personalrelation',
            name='to_speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_speaker', to='info.Speaker'),
        ),
        migrations.AddField(
            model_name='locationrelation',
            name='to_speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Speaker'),
        ),
        migrations.AddField(
            model_name='languagerelation',
            name='to_speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Speaker'),
        ),
        migrations.AddField(
            model_name='dialect',
            name='to_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Language'),
        ),
    ]
