# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20160616_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
