"""
Django settings for trimco project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

SITE_ID = 1
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'k+3ipyx)=c)_o_%z4_ybnp#7_0#f3bdt#e*gox_^cf7cw#)p+t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['https://vmd16147.contabo.host:10000/']


# Application definition

INSTALLED_APPS = (

    # GRAPPELLI
    'grappelli',

    # DJANGO NATIVE
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.redirects',

    # LOCAL
    'info',
    'corpora',
    'morphology',
    'queries',

    # ADDITIONAL
    'django_ajax',
    "geoposition",
    'django_cleanup',
    'reversion',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.redirects.middleware.RedirectFallbackMiddleware',
)

ROOT_URLCONF = 'trimco.urls'

if 'OPENSHIFT_REPO_DIR' in os.environ:
    DIRS = os.path.join(os.environ.get('OPENSHIFT_REPO_DIR'), 'trimco', 'data', 'static', 'templates')
else:
    DIRS = os.path.join(BASE_DIR, 'data', 'static', 'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [DIRS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trimco.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

#STATIC_ROOT = BASE_DIR+'/static/_root/'

if 'OPENSHIFT_REPO_DIR' in os.environ:
    STATIC_ROOT = os.path.join(os.environ.get('OPENSHIFT_REPO_DIR'), 'trimco', 'data', 'static')
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'data', STATIC_URL.strip("/"))

#STATICFILES_DIRS = [BASE_DIR+'/static/_root/addons/']

if 'OPENSHIFT_REPO_DIR' in os.environ:
    STATICFILES_DIRS = [os.path.join(os.environ.get('OPENSHIFT_REPO_DIR'), 'trimco', 'data', 'static', '_root', 'addons')]
else:
    STATICFILES_DIRS = [BASE_DIR+'/data/static/_root/addons/']

#MEDIA_ROOT = BASE_DIR+'/media/'
if 'OPENSHIFT_REPO_DIR' in os.environ:
    MEDIA_ROOT = os.path.join(os.environ.get('OPENSHIFT_REPO_DIR'), 'trimco', 'data', 'media')
else:
    MEDIA_ROOT = os.path.join(BASE_DIR, 'data', MEDIA_URL.strip("/"))


GRAPPELLI_ADMIN_TITLE = 'BaltSlavDialects 0.1'
